### ISSUE TITLE
Error when running composer reqiure

### ISSUE THREAD

**Issue by tminsaas** [Siteimprove/cms-plugin-ezplatform#2]
I'm trying to install this bundle on a ezplatform v. 1.12 installation using the composer command from instructions:

 php composer.phar require siteimprove/cms-plugin-ezplatform

But the installation halts with the following error message:

 [InvalidArgumentException]
  Could not find package siteimprove/cms-plugin-ezplatform at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Any tips?

**Comment by Plopix** [comment]
Hello @tminsaas,

The plugin has not been tagged yet, that is why you have this error.
`php composer.phar require siteimprove/cms-plugin-ezplatform:dev-master` will do the job waiting for a tag "stable".

@Finnbjorn should we tag a 1.0.0?
